# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [10]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [12]:
grades = np.array( [77, 85, 56, 90, 66])
print(np.average(grades))

74.8


### 【示範】陣列導向

最大值

In [9]:
print(np.max(grades))

90


標準差

In [11]:
print(np.std(grades))

12.416118556135006


### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [33]:
prices = [1096.95, 596.95, 896.95]
prices_ntd = []
for item in prices:
    prices_ntd.append(item * 31.71) 
print(prices_ntd)

[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [17]:
prices_array = np.array(prices)
print(prices_array * 31.71)

[34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [15]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [42]:
weighted_grades=np.multiply(grades,weights)
print(weighted_grades)

[17.  24.5 36. ]
<class 'numpy.ndarray'>


### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [17]:
weighted_grades = weights * grades
weighted_grades.sum()

77.5

### 【技巧】 一行完成成績計算

In [19]:
np.dot(grades, weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [21]:
A = np.random.rand(50)
A

array([0.98695107, 0.42996756, 0.49559532, 0.38654544, 0.67416333,
       0.11933539, 0.97072655, 0.08070904, 0.91021333, 0.47161026,
       0.63644014, 0.33745541, 0.58068311, 0.90660817, 0.68437889,
       0.94784864, 0.53733956, 0.08281651, 0.56299663, 0.71281264,
       0.99332064, 0.58887603, 0.47568682, 0.79167055, 0.41362843,
       0.03117241, 0.68091196, 0.01129583, 0.18671987, 0.00950417,
       0.47175764, 0.01958653, 0.88053807, 0.76778478, 0.73703114,
       0.27068983, 0.10479218, 0.92132649, 0.43744606, 0.90039524,
       0.49980602, 0.65963536, 0.78720188, 0.10508094, 0.567864  ,
       0.82875359, 0.95918432, 0.36028786, 0.11451329, 0.70146764])

### 【技巧】 檢查 A 的 `shape`

In [22]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [23]:
A.shape = 5,10
A

array([[0.98695107, 0.42996756, 0.49559532, 0.38654544, 0.67416333,
        0.11933539, 0.97072655, 0.08070904, 0.91021333, 0.47161026],
       [0.63644014, 0.33745541, 0.58068311, 0.90660817, 0.68437889,
        0.94784864, 0.53733956, 0.08281651, 0.56299663, 0.71281264],
       [0.99332064, 0.58887603, 0.47568682, 0.79167055, 0.41362843,
        0.03117241, 0.68091196, 0.01129583, 0.18671987, 0.00950417],
       [0.47175764, 0.01958653, 0.88053807, 0.76778478, 0.73703114,
        0.27068983, 0.10479218, 0.92132649, 0.43744606, 0.90039524],
       [0.49980602, 0.65963536, 0.78720188, 0.10508094, 0.567864  ,
        0.82875359, 0.95918432, 0.36028786, 0.11451329, 0.70146764]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [24]:
A.reshape(10,5)

array([[0.98695107, 0.42996756, 0.49559532, 0.38654544, 0.67416333],
       [0.11933539, 0.97072655, 0.08070904, 0.91021333, 0.47161026],
       [0.63644014, 0.33745541, 0.58068311, 0.90660817, 0.68437889],
       [0.94784864, 0.53733956, 0.08281651, 0.56299663, 0.71281264],
       [0.99332064, 0.58887603, 0.47568682, 0.79167055, 0.41362843],
       [0.03117241, 0.68091196, 0.01129583, 0.18671987, 0.00950417],
       [0.47175764, 0.01958653, 0.88053807, 0.76778478, 0.73703114],
       [0.27068983, 0.10479218, 0.92132649, 0.43744606, 0.90039524],
       [0.49980602, 0.65963536, 0.78720188, 0.10508094, 0.567864  ],
       [0.82875359, 0.95918432, 0.36028786, 0.11451329, 0.70146764]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [25]:
np.ravel(A)

array([0.98695107, 0.42996756, 0.49559532, 0.38654544, 0.67416333,
       0.11933539, 0.97072655, 0.08070904, 0.91021333, 0.47161026,
       0.63644014, 0.33745541, 0.58068311, 0.90660817, 0.68437889,
       0.94784864, 0.53733956, 0.08281651, 0.56299663, 0.71281264,
       0.99332064, 0.58887603, 0.47568682, 0.79167055, 0.41362843,
       0.03117241, 0.68091196, 0.01129583, 0.18671987, 0.00950417,
       0.47175764, 0.01958653, 0.88053807, 0.76778478, 0.73703114,
       0.27068983, 0.10479218, 0.92132649, 0.43744606, 0.90039524,
       0.49980602, 0.65963536, 0.78720188, 0.10508094, 0.567864  ,
       0.82875359, 0.95918432, 0.36028786, 0.11451329, 0.70146764])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [3]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 【技巧】 都是 1 的 array

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [26]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### 【技巧】給定範圍均勻生出 n 個點

In [28]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [34]:
A=np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [35]:
A.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [36]:
A.sum(axis=1)

array([10, 35])

### 【提示】當然也有可能全部算

In [37]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [55]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [39]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [40]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [42]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [43]:
L[L>0]

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [68]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[3:5]

array([3, 4])

### 【技巧】2維陣列切法

記得先列後行!

In [71]:
y=x.reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [72]:
y[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [73]:
y[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [74]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [81]:
X=np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [78]:
Y=np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [82]:
X[:,0]

array([1, 2, 3, 4])